### ISSUE TITLE
Insecure Guidance

### ISSUE THREAD

**Issue by QuinnyPig** [aws-samples/aws-appsync-ai-agent-playground-blog-sample#4]
I am but a humble Cloud Economist, but isn't this suggestion:

```
If you want to use openai create the file handler-openai-streaming/.env with content like:
OPENAI_SECRET_KEY=sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

pants-shittingly insecure, and contrary to existing AWS Security best practices? Further, given that half of creation and also people's housepets are using OpenAI, isn't this a fantastic opportunity to do an under-the-hood integration between Secrets Manager / Parameter Store to natively store OpenAI API Keys as a part of the Bedrock service?

**Comment by mtliendo** [comment]
Hey Corey! My coworker and I spent a lot of time on this, so it's good to get your feedback.

The OpenAI part of this app is part of a local playground environment that is deployed along the core of the app. But to your point, I missed adding that to the .gitignore (now updated)--your're right though, we should add it to the Parameter Store. I removed the reference in the readme and will update the code soon to show that.

Thanks for the quick-to-comment and looking forward to seeing you at re:invent.
